@startuml PlantUMLApp
title PlantUMLApp
class PlantUMLApp #GhostWhite {
- {static} string _projectspath
- {static} string _targetpath
- DiagramBuilderType _diagrambuilder
- string _diagramfolder
- bool _createcompletediagram
- int _maxgenerationdepth
---
+ {static} string getProjectsPath()
+ {static} Void setProjectsPath(string value)
+ {static} string getTargetPath()
+ {static} Void setTargetPath(string value)
+ DiagramBuilderType getDiagramBuilder()
+ Void setDiagramBuilder(DiagramBuilderType value)
+ string getDiagramFolder()
+ Void setDiagramFolder(string value)
+ bool getCreateCompleteDiagram()
+ Void setCreateCompleteDiagram(bool value)
+ int getMaxGenerationDepth()
+ Void setMaxGenerationDepth(int value)
---
- {static} void ClassConstructing()
- {static} void ClassConstructed()
- void Constructing()
- void Constructed()
# MenuItem[] CreateMenuItems()
# void PrintHeader()
+ void Run(string[] args)
- void ChangeDiagramFolder()
+ void ChangeMaxGenerationDepth()
- void ChangeDiagramBuilder()
- void CreateDiagram(MenuItem menuItem, bool force)
}
ConsoleApplication <|-- PlantUMLApp
' CustomUML
abstract class ConsoleApplication #LightBlue {
}
' CustomUML
@enduml
