@startuml DiagramCreator.CreateCollectionState
title DiagramCreator.CreateCollectionState
start
#LightGreen:Params(IEnumerable collection);
#LightSkyBlue:var counter = 0\nvar result = new List<string>();
:iterator = collection.GetIterator();
while (iterator.MoveNext()) is (<color:green>yes)
  :item = iterator.Current();
    #LightYellow:if (item != null) then (<color:green>yes)
      #WhiteSmoke:result.Add($"{counter++} => {item.GetType().Name}_{item.GetHashCode()}");
      else (<color:red>no)
        #WhiteSmoke:result.Add($"{counter++} => null");
    endif
endwhile (<color:red>no)
#Lavender:return result;
stop
@enduml
