@startuml DiagramCreator.ReadCustomUML
title DiagramCreator.ReadCustomUML
start
#LightGreen:Params(IEnumerable<string> lines);
#LightSkyBlue:var result = new List<string>()\nvar counter = 0;
:iterator = lines.GetIterator();
while (iterator.MoveNext()) is (<color:green>yes)
  :line = iterator.Current();
    #LightYellow:if (line.StartsWith($"'{CustomUMLLabel}", StringComparison.CurrentCultureIgnoreCase) || line.StartsWith($"' {CustomUMLLabel}", StringComparison.CurrentCultureIgnoreCase)) then (<color:green>yes)
      #WhiteSmoke:counter++;
      else (<color:red>no)
        #LightYellow:if (counter > 0 && counter % 2 > 0) then (<color:green>yes)
          #WhiteSmoke:result.Add(line);
        endif
    endif
endwhile (<color:red>no)
#Lavender:return result;
' CustomUML
      #WhiteSmoke:counter++;
      else (<color:red>no)
        #LightYellow:if (counter > 0 && counter % 2 > 0) then (<color:green>yes)
          #WhiteSmoke:result.Add(line);
        endif
    endif
endwhile (<color:red>no)
#Lavender:return result;
stop
@enduml
' CustomUML
stop
@enduml
