@startuml DiagramCreator.CreateActivityDiagram
title DiagramCreator.CreateActivityDiagram
participant "CreateActivityDiagram(string path,string source,bool force)" as CreateActivityDiagram_p0_p1_p2 #LightYellow
participant "CreateActivityDiagram(a0,a1,a2,a3,a4)" as CreateActivityDiagram_a0_a1_a2_a3_a4 #LightGreen
autonumber
CreateActivityDiagram_p0_p1_p2 -[#grey]> CreateActivityDiagram_a0_a1_a2_a3_a4 : (path, source, [], false, force)
@enduml
