@startuml DiagramCreator.CreateActivityDiagram
title DiagramCreator.CreateActivityDiagram
participant "CreateActivityDiagram(string path,string source,string[] defines,bool declarations,bool force)" as CreateActivityDiagram_p0_p1_p2_p3_p4 #LightYellow
participant "CSharpSyntaxTree.ParseText(a0,a1)" as CSharpSyntaxTree_ParseText_a0_a1 #LightGreen
participant "syntaxTree.GetRoot()" as syntaxTree_GetRoot #LightGreen
participant "syntaxRoot.DescendantNodes().OfType<ClassDeclarationSyntax>()" as syntaxRoot_DescendantNodes_OfType_ClassDeclarationSyntax_ #LightGreen
participant "syntaxRoot.DescendantNodes()" as syntaxRoot_DescendantNodes #LightGreen
participant "Path.Exists(a0)" as Path_Exists_a0 #LightGreen
participant "Directory.CreateDirectory(a0)" as Directory_CreateDirectory_a0 #LightGreen
participant "classNode.DescendantNodes().OfType<MethodDeclarationSyntax>()" as classNode_DescendantNodes_OfType_MethodDeclarationSyntax_ #LightGreen
participant "classNode.DescendantNodes()" as classNode_DescendantNodes #LightGreen
participant "CreateActivityDiagram(a0,a1)" as CreateActivityDiagram_a0_a1 #LightGreen
participant "infoData.Contains(a0)" as infoData_Contains_a0 #LightGreen
participant "Path.Combine(a0,a1)" as Path_Combine_a0_a1 #LightGreen
participant "diagramData.AddRange(a0)" as diagramData_AddRange_a0 #LightGreen
participant "ReadCustomUMLFromFle(a0)" as ReadCustomUMLFromFle_a0 #LightGreen
participant "diagramData.Insert(a0,a1)" as diagramData_Insert_a0_a1 #LightGreen
participant "diagramData.Add(a0)" as diagramData_Add_a0 #LightGreen
participant "File.WriteAllLines(a0,a1)" as File_WriteAllLines_a0_a1 #LightGreen
participant "infoData.Add(a0)" as infoData_Add_a0 #LightGreen
participant "UpdateDiagramPath(a0,a1)" as UpdateDiagramPath_a0_a1 #LightGreen
autonumber
CreateActivityDiagram_p0_p1_p2_p3_p4 -[#grey]> CSharpSyntaxTree_ParseText_a0_a1 : (source, options)
CSharpSyntaxTree_ParseText_a0_a1 -[#blue]-> CreateActivityDiagram_p0_p1_p2_p3_p4 : syntaxTree
CreateActivityDiagram_p0_p1_p2_p3_p4 -[#grey]> syntaxTree_GetRoot
syntaxTree_GetRoot -[#blue]-> CreateActivityDiagram_p0_p1_p2_p3_p4 : syntaxRoot
CreateActivityDiagram_p0_p1_p2_p3_p4 -[#grey]> syntaxRoot_DescendantNodes_OfType_ClassDeclarationSyntax_
syntaxRoot_DescendantNodes_OfType_ClassDeclarationSyntax_ -[#blue]-> CreateActivityDiagram_p0_p1_p2_p3_p4 : classNodes
alt#LightBlue Path.Exists(path) == false
 CreateActivityDiagram_p0_p1_p2_p3_p4 -[#grey]> Path_Exists_a0 : (path)
 CreateActivityDiagram_p0_p1_p2_p3_p4 -[#grey]> Directory_CreateDirectory_a0 : (path)
end
loop#LightCoral classNodes
 CreateActivityDiagram_p0_p1_p2_p3_p4 -[#grey]> classNode_DescendantNodes_OfType_MethodDeclarationSyntax_
 classNode_DescendantNodes_OfType_MethodDeclarationSyntax_ -[#blue]-> CreateActivityDiagram_p0_p1_p2_p3_p4 : methodNodes
 loop#LightCoral methodNodes
 CreateActivityDiagram_p0_p1_p2_p3_p4 -[#grey]> CreateActivityDiagram_a0_a1 : (methodNode, declarations)
 CreateActivityDiagram_a0_a1 -[#blue]-> CreateActivityDiagram_p0_p1_p2_p3_p4 : diagramData
 alt#LightBlue infoData.Contains($"{nameof(fileName)}:{fileName}{PlantUMLExtension}") == false
 CreateActivityDiagram_p0_p1_p2_p3_p4 -[#grey]> infoData_Contains_a0 : ($"{nameof(fileName)}:{fileName}{PlantUMLExtension}")
 end
 CreateActivityDiagram_p0_p1_p2_p3_p4 -[#grey]> Path_Combine_a0_a1 : (path, fileName)
 Path_Combine_a0_a1 -[#blue]-> CreateActivityDiagram_p0_p1_p2_p3_p4 : filePath
 CreateActivityDiagram_p0_p1_p2_p3_p4 -[#grey]> diagramData_AddRange_a0 : (ReadCustomUMLFromFle(filePath))
 diagramData_AddRange_a0 -[#grey]> ReadCustomUMLFromFle_a0 : (ReadCustomUMLFromFle(filePath))
 CreateActivityDiagram_p0_p1_p2_p3_p4 -[#grey]> diagramData_Insert_a0_a1 : (0, $"@{StartUmlLabel} {title}")
 CreateActivityDiagram_p0_p1_p2_p3_p4 -[#grey]> diagramData_Insert_a0_a1 : (1, $"title {title}")
 CreateActivityDiagram_p0_p1_p2_p3_p4 -[#grey]> diagramData_Insert_a0_a1 : (2, "start")
 CreateActivityDiagram_p0_p1_p2_p3_p4 -[#grey]> diagramData_Add_a0 : ("stop")
 CreateActivityDiagram_p0_p1_p2_p3_p4 -[#grey]> diagramData_Add_a0 : ($"@{EndUmlLabel}")
 alt#LightBlue force || Path.Exists(filePath) == false
 CreateActivityDiagram_p0_p1_p2_p3_p4 -[#grey]> Path_Exists_a0 : (filePath)
 CreateActivityDiagram_p0_p1_p2_p3_p4 -[#grey]> File_WriteAllLines_a0_a1 : (filePath, diagramData)
 end
 CreateActivityDiagram_p0_p1_p2_p3_p4 -[#grey]> infoData_Add_a0 : ($"{nameof(title)}:{title} (AC)")
 CreateActivityDiagram_p0_p1_p2_p3_p4 -[#grey]> infoData_Add_a0 : ($"{nameof(fileName)}:{fileName}")
 CreateActivityDiagram_p0_p1_p2_p3_p4 -[#grey]> infoData_Add_a0 : ($"generated_on:{DateTime.UtcNow}")
 CreateActivityDiagram_p0_p1_p2_p3_p4 -[#grey]> infoData_Add_a0 : ($"generated_by:generated with the DiagramCreator by Prof.Gehrer")
 end
end
alt#LightBlue force || Path.Exists(Path.Combine(path, infoFileName)) == false
 CreateActivityDiagram_p0_p1_p2_p3_p4 -[#grey]> Path_Exists_a0 : (Path.Combine(path, infoFileName))
 Path_Exists_a0 -[#grey]> Path_Combine_a0_a1 : (Path.Combine(path, infoFileName))
 CreateActivityDiagram_p0_p1_p2_p3_p4 -[#grey]> File_WriteAllLines_a0_a1 : (Path.Combine(path, infoFileName), infoData)
 File_WriteAllLines_a0_a1 -[#grey]> Path_Combine_a0_a1 : (Path.Combine(path, infoFileName), infoData)
 CreateActivityDiagram_p0_p1_p2_p3_p4 -[#grey]> UpdateDiagramPath_a0_a1 : (path, InfoFileFilter)
end
@enduml
